import { db } from './index.ts';
import { users, profiles, follows } from './schema.ts';
import { sql } from 'drizzle-orm';

export async function seedPostgresIfEmpty() {
  try {
    const existingUsers = await db.select({ count: sql<number>`count(*)::int` }).from(users);
    if ((existingUsers[0]?.count || 0) > 0) {
      console.log('[Postgres Seed] Users table already populated with', existingUsers[0].count, 'users.');
      return;
    }

    console.log('[Postgres Seed] Seeding initial users and profiles into PostgreSQL...');
    const now = new Date();

    const sampleUsersData = [
      {
        user: {
          id: 'usr_admin_01',
          email: 'admin@globalmatch.com',
          password: 'admin123_demo_hashed',
          role: 'ADMIN',
          isEmailVerified: 1,
          isAgeVerified: 1,
          isBanned: 0,
          subscriptionTier: 'VIP',
          createdAt: now,
          updatedAt: now,
        },
        profile: {
          id: 'prf_admin_01',
          userId: 'usr_admin_01',
          sourceType: 'native',
          name: 'System Administrator',
          age: 32,
          dateOfBirth: '1994-01-01',
          gender: 'MALE',
          country: 'Global',
          city: 'Global HQ',
          region: 'Main',
          approxDistanceKm: 0,
          bio: 'Platform Administrator and Community Manager at GlobalMatch.',
          coverPhoto: 'https://images.unsplash.com/photo-1707343843437-caacff5cfa74?auto=format&fit=crop&w=1600&q=80',
          photosJson: JSON.stringify(['https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=1000&q=80']),
          interestsJson: JSON.stringify(['Security', 'Cloud Tech', 'Global Community']),
          languagesJson: JSON.stringify(['English']),
          relationshipGoal: 'System Management',
          compatibilityScore: 100,
          isOnline: 1,
          lastActive: now.toISOString(),
          isVerified: 1,
          isBoosted: 0,
          isVisible: 1,
          showAge: 1,
          showApproxLocation: 0,
          allowCalls: 1,
          allowMessages: 1,
          createdAt: now.toISOString(),
          updatedAt: now.toISOString(),
        }
      },
      {
        user: {
          id: 'usr_nat_01',
          email: 'anika.rahman@example.com',
          password: 'demo_password_123',
          role: 'USER',
          isEmailVerified: 1,
          isAgeVerified: 1,
          isBanned: 0,
          subscriptionTier: 'PREMIUM',
          createdAt: now,
          updatedAt: now,
        },
        profile: {
          id: 'prf_nat_01',
          userId: 'usr_nat_01',
          sourceType: 'native',
          name: 'Anika Rahman',
          age: 25,
          dateOfBirth: '2001-08-14',
          gender: 'FEMALE',
          country: 'Bangladesh',
          city: 'Dhaka',
          region: 'Gulshan',
          approxDistanceKm: 12,
          bio: 'Software engineer at a fintech startup. I love classical Rabindra Sangeet, brewing artisan tea, and exploring historical architecture around old Dhaka. Always up for a thoughtful conversation and a good cup of chai.',
          coverPhoto: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=80',
          photosJson: JSON.stringify([
            'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=1000&q=80',
            'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=1000&q=80',
          ]),
          interestsJson: JSON.stringify(['Tech & AI', 'Tea Ceremonies', 'Music', 'Literature', 'Travel']),
          languagesJson: JSON.stringify(['Bengali', 'English']),
          relationshipGoal: 'Long-term relationship',
          education: 'B.Sc in Computer Science, BUET',
          profession: 'Senior Frontend Engineer',
          height: 165,
          smoking: 'Never',
          drinking: 'Never',
          children: 'Want someday',
          compatibilityScore: 96,
          isOnline: 1,
          lastActive: now.toISOString(),
          isVerified: 1,
          isBoosted: 1,
          isVisible: 1,
          showAge: 1,
          showApproxLocation: 1,
          allowCalls: 1,
          allowMessages: 1,
          createdAt: now.toISOString(),
          updatedAt: now.toISOString(),
        }
      },
      {
        user: {
          id: 'usr_nat_02',
          email: 'elena.vidal@example.com',
          password: 'demo_password_123',
          role: 'USER',
          isEmailVerified: 1,
          isAgeVerified: 1,
          isBanned: 0,
          subscriptionTier: 'VIP',
          createdAt: now,
          updatedAt: now,
        },
        profile: {
          id: 'prf_nat_02',
          userId: 'usr_nat_02',
          sourceType: 'native',
          name: 'Elena Vidal',
          age: 26,
          dateOfBirth: '2000-03-22',
          gender: 'FEMALE',
          country: 'Spain',
          city: 'Barcelona',
          region: 'Eixample',
          approxDistanceKm: 45,
          bio: 'Contemporary ceramic artist and Mediterranean foodie. Passionate about coastal runs, indie cinema, and cooking paella for close friends on Sunday afternoons.',
          coverPhoto: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1600&q=80',
          photosJson: JSON.stringify([
            'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1000&q=80',
            'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=1000&q=80',
          ]),
          interestsJson: JSON.stringify(['Ceramics', 'Culinary Arts', 'Beach Volleyball', 'Cinema', 'Design']),
          languagesJson: JSON.stringify(['Spanish', 'Catalan', 'English', 'French']),
          relationshipGoal: 'Long-term partner',
          education: 'Fine Arts Degree, University of Barcelona',
          profession: 'Ceramics Designer & Studio Owner',
          height: 170,
          smoking: 'Never',
          drinking: 'Socially',
          children: 'Open to children',
          compatibilityScore: 91,
          isOnline: 1,
          lastActive: now.toISOString(),
          isVerified: 1,
          isBoosted: 0,
          isVisible: 1,
          showAge: 1,
          showApproxLocation: 1,
          allowCalls: 1,
          allowMessages: 1,
          createdAt: now.toISOString(),
          updatedAt: now.toISOString(),
        }
      },
      {
        user: {
          id: 'usr_nat_03',
          email: 'lucas.becker@example.com',
          password: 'demo_password_123',
          role: 'USER',
          isEmailVerified: 1,
          isAgeVerified: 1,
          isBanned: 0,
          subscriptionTier: 'FREE',
          createdAt: now,
          updatedAt: now,
        },
        profile: {
          id: 'prf_nat_03',
          userId: 'usr_nat_03',
          sourceType: 'native',
          name: 'Lucas Becker',
          age: 29,
          dateOfBirth: '1997-11-05',
          gender: 'MALE',
          country: 'Germany',
          city: 'Berlin',
          region: 'Mitte',
          approxDistanceKm: 30,
          bio: 'Renewable energy consultant and amateur marathon runner. Love weekend cycling tours along the Spree, modular synthesis, and pour-over coffee.',
          coverPhoto: 'https://images.unsplash.com/photo-1477959858617-67f30bc75b82?auto=format&fit=crop&w=1600&q=80',
          photosJson: JSON.stringify([
            'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=1000&q=80',
            'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=1000&q=80',
          ]),
          interestsJson: JSON.stringify(['Marathon', 'Clean Tech', 'Electronic Music', 'Philosophy', 'Coffee']),
          languagesJson: JSON.stringify(['German', 'English']),
          relationshipGoal: 'Long-term relationship',
          education: 'M.Sc in Environmental Engineering, TU Berlin',
          profession: 'Climate Tech Lead',
          height: 182,
          smoking: 'Never',
          drinking: 'Socially',
          children: 'Want someday',
          compatibilityScore: 89,
          isOnline: 0,
          lastActive: now.toISOString(),
          isVerified: 1,
          isBoosted: 0,
          isVisible: 1,
          showAge: 1,
          showApproxLocation: 1,
          allowCalls: 1,
          allowMessages: 1,
          createdAt: now.toISOString(),
          updatedAt: now.toISOString(),
        }
      },
      {
        user: {
          id: 'usr_nat_04',
          email: 'maya.lin@example.com',
          password: 'demo_password_123',
          role: 'USER',
          isEmailVerified: 1,
          isAgeVerified: 1,
          isBanned: 0,
          subscriptionTier: 'PREMIUM',
          createdAt: now,
          updatedAt: now,
        },
        profile: {
          id: 'prf_nat_04',
          userId: 'usr_nat_04',
          sourceType: 'native',
          name: 'Maya Lin',
          age: 27,
          dateOfBirth: '1999-04-18',
          gender: 'FEMALE',
          country: 'Singapore',
          city: 'Singapore',
          region: 'Marina Bay',
          approxDistanceKm: 60,
          bio: 'Fintech product manager and scuba diving enthusiast. Enjoy exploring street food gems across SE Asia, practicing yoga at sunrise, and reading historical fiction.',
          coverPhoto: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1600&q=80',
          photosJson: JSON.stringify([
            'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1000&q=80',
            'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1000&q=80',
          ]),
          interestsJson: JSON.stringify(['Scuba Diving', 'Fintech', 'Yoga', 'Culinary Travel', 'Books']),
          languagesJson: JSON.stringify(['English', 'Mandarin']),
          relationshipGoal: 'Marriage & Family',
          education: 'B.BA, National University of Singapore',
          profession: 'Product Lead',
          height: 168,
          smoking: 'Never',
          drinking: 'Socially',
          children: 'Want children',
          compatibilityScore: 94,
          isOnline: 1,
          lastActive: now.toISOString(),
          isVerified: 1,
          isBoosted: 0,
          isVisible: 1,
          showAge: 1,
          showApproxLocation: 1,
          allowCalls: 1,
          allowMessages: 1,
          createdAt: now.toISOString(),
          updatedAt: now.toISOString(),
        }
      }
    ];

    for (const item of sampleUsersData) {
      await db.insert(users).values(item.user).onConflictDoNothing();
      await db.insert(profiles).values(item.profile).onConflictDoNothing();
    }

    // Seed some initial follow connections
    await db.insert(follows).values([
      { id: 'fol_init_01', followerId: 'usr_nat_02', followingId: 'usr_nat_01' },
      { id: 'fol_init_02', followerId: 'usr_nat_03', followingId: 'usr_nat_01' },
      { id: 'fol_init_03', followerId: 'usr_nat_04', followingId: 'usr_nat_01' },
      { id: 'fol_init_04', followerId: 'usr_nat_01', followingId: 'usr_nat_02' },
      { id: 'fol_init_05', followerId: 'usr_nat_01', followingId: 'usr_nat_04' },
    ]).onConflictDoNothing();

    console.log('[Postgres Seed] Successfully seeded default users and follow relationships.');
  } catch (err) {
    console.error('[Postgres Seed] Error during seed:', err);
  }
}
